apiVersion: apps/v1
kind: Deployment
metadata:
    name: react-docker-container
    labels:
        app: react-docker-container
spec:
    replicas: 2
    selector:
        matchLabels: 
            app: react-docker-container
    template:
        metadata:
            labels:
                app: react-docker-container
        spec:
            containers:
            -   name: react-docker-container
                image: magnolialabs/react-docker-container
                ports:
                -   containerPort: 80 
                resources:
                    limits:
                        memory: '128Mi'
                        cpu: '200m'
                livenessProbe:
                    httpGet:
                        path: /index.html
                        port: 80
                    initialDelaySeconds: 15
                    timeoutSeconds: 2
                    periodSeconds: 5
                    failureThreshold: 1
                readinessProbe:
                    httpGet:
                        path: /index.html
                        port: 80
                    initialDelaySeconds: 15
                    periodSeconds: 5
                    failureThreshold: 1